#!/usr/bin/env bash
rm -rf public
npx antora local-playbook.yml 
cp  css/kurt-customizations.css public/_/css/
cp  fonts/* public/_/font/
/usr/bin/rm -rf /var/www/krueckeberg.org/nla/*
/usr/bin/cp -r public /var/www/krueckeberg.org/nla
/usr/bin/chown -R root:www-data /var/www/krueckeberg.org/nla
/usr/bin/chmod -R g+w /var/www/krueckeberg.org/nla
