site:
  title: Krückeberg and Bleeke Genealogy Research Topics
  start_page: nla-docs:1237:index.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      edit_url: false

asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    allow-uri-read: "yes"
    icons: font
    sectnums: true
    pdf-theme: default
    pdf-themesdir: ./themes

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/pdf

