= Todoes

== Initials

Figure out the Amt intials vs the Rentcammer initials

1. The Amt background document has these intials: Hauck, Höcke
2. todo

== Document 10

Complete its styling.

== Switch to [verse] blocks

And use {nbsp} within [verse] blocks. Left-align the text and use descriptions of the positions
to indicate where the text is.

== Document 4

Use chatgpt to analys the block of text to the bottom of the 2nd document that continues
onto the next page.

. the three initials looks familiar. They are likely the 3 Rentcammer officials. Check
other documents for the same initals. Find clearer versions
. this 2nd block of text written in a different hand

== Document 6

Do the headers I have chosen don't match the descriptions given in the Acten Designation?

== Document 8 has a different Num Pr number

...than document 1.

== Analyze This Way

Resume with "analyze.adoc" and this ChatGPT session: https://chatgpt.com/c/68df17e0-6164-8323-9013-291141655388,

TODO: Link document 2 and 3.

* document 3 is Krückeberg follow-up request to the Amt's report. That report refused to support install payments
that Krückeberg that would pay to Hempel and Sons. They had already decided the case warranted the seizure and
forced sale of his property. They did agree to permit him to take out a loan from the government, so Hempel and
Sons could be paid immediately, which he would have to pay back to the government.

Consult other-numbering-notes.adoc

