= Todoes

== NLA Module 689

=== Do Tranlstion of  "Exp"/"expidiert"

Find the instances of 'Exp' like, for example
...
Exp
Holste (or some other name)
17/11 (or some other date)
...

by searching for: pc '[Ee]xp' ~/nla/m/689/p/*.adoc

Then Translate it as: "sent out by Holsteo on NOv. 17th"

=== Create a page for explanation of terms and concepts

...like Rescript, dispoistive comments, an overview of the role of the Amt and Rentcammer, whether Krueckeberg
finally appeals to "Ceasar".

Add a glossary-like page, but rather than merely or purely a glossary, such a glossary.adoc, create an explanation of terms
and concepts that builds on what is in glossary.adoc and overview.adocp[]

Add this page(s) to nav.adoc.

=== Other Thoughts

Make sure:
* transliterations and translations content matches
* they are not missing content found in the image(s). 
* they logically reflect the image's content
* there are necessary explanations of terms
* The initials are explained (see below)
* There is an overall summary of synopsis

Chatgpt link for analyzing documents: https://chatgpt.com/c/68df17e0-6164-8323-9013-291141655388 

=== Initials

Figure out the Amt intials vs the Rentcammer initials

1. The Amt background document has these intials: Hauck, Höcke
2. The Rentcammer has these intials: ?, ?, ?


Höcker - Amtsdiener
Reck   - Senior Privy Councilor

=== Explain Terms and Concepts

The terms in contents list, the glossary, and in the docketing information.

== Translations

Base the translation on transliteration with updated words for archaic words.
