= todoes

== Switch to [verse] blocks

And use {nbsp} within [verse] blocks. Left-align the text and use descriptions of the positions
to indicate where the text is.


== Document 4

USe chatgpt to analys the 2nd document in #4 and its:

. three blocks of text
. the initials
. the 2rd block written in a different hand
. The unclear H[??] initial and whether it occurs in a nother document?

== Document 8 has a different Num Pr number

...than document 1.

== Analyze This Way

Resume with "analyze.adoc" and this ChatGPT session: https://chatgpt.com/c/68df17e0-6164-8323-9013-291141655388,

TODO: Link document 2 and 3.

* document 3 is Krückeberg follow-up request to the Amt's report. That report refused to support install payments
that Krückeberg that would pay to Hempel and Sons. They had already decided the case warranted the seizure and
forced sale of his property. They did agree to permit him to take out a loan from the government, so Hempel and
Sons could be paid immediately, which he would have to pay back to the government.

Consult other-numbering-notes.adoc

