= Todoes


== Review 1291 documents

Resume with doc #6 ancillary documents.

== NLA 147, No. 19 Berenbusch

This case file mention "Krückberg of no. 18 Berenbusch", and it shows his
his Stätte of No. 18 Berembusch on a survery drawing, which would be very
worthwhile using.

== Finish Review Moehle Work

Examine and analyze it, creating .adoc pages as I go.

== Add Jobst Heinrich Weyland Results from Moehle Work to NLA

See the first five images from the NLA document. 

== Rottzinß

This term appears clearly in `~/nla/m/1237/p/doc4.adoc`. I believe this is
the term that should be used in documents in `~/nla/m/146/p`.

== Work through new Case File in ~/backup

It is located in ~/backup_folder/2026-01-15_Auftrag_Krückeberg_2026-01-21_145514.zip

== Case File 188

The contents of case file 188

== Module 139: Analyze Image Sections

. For each Designatio Actorum item decide which part of which image is the
text for the Designatio Actorum item. Make sure we account for all the text
in all the images. Make sure we understand each part of each image.
. Review the Overviews for each .adoc page.
. Make notes of what is genealogically and historically of value.

== Ask Chatgpt about "Docket Item" for Module 689

I'm not sure that "Docket Item" is correct for these documents. I also
believe--I think--that the last column in the Designatio Actorum is the
Tag/Day even though the column has what appears to be a "Z". I believe it
is the "day" because it does corresponds to the day given in the date on
the document.

== Confirm Dates

For the document listed in m/146/p/other-docs.adoc confirm the dates when they documents were written
not when they were presented in the chamber.

== Images

https://chatgpt.com/share/694a151e-c5e0-8004-afd1-d9cb5dc943eb

The only further thing to confirm is the asterisked text on the lower left.

== Big Picture

Read about Schaumburg-Lippe in German and English, read about Anerbenrecht, read about the material
on the Arbeitsgemeinschaft von Schaumburg-Lippe website. Read all I can to be a basic understanding
of its government and how it functioned for the average blue collar worker.

== 1237

=== Narrative Timeline

TODO: 

. Reconfirm if the `reminder-note.adoc` 's date of 27 Dec. 1800 is the same as Document #5, and whether the
Reminder Note belongs with the document #5 cluster of documents?
. The Narrative Time needs document #6 added to it. 
. According to my narrative summary, which was generated by ChatGPT, document #6 was written by the 
Comital Guardianship Treasury Office (Gräflich vormundschaftliche Rentkammer). Is this the same as the 
Vormundschaftliche Kammer mentioned in the other documents, which I thought was the only chamber involved and
that the Rentkammer was not involed?

== Organize 139's doc1 and doc2

FINISH Transliterations and Translations.

Document #1 page is very busy and poorly organized. It is not readily understandable, not 'friendly'.
Do this:

* provide a default width -- using `[.narrow]` -- of the petition of widow Krückeberg as well
  as the Rentkammers dispositive comment.
* Use h2 and h3 labels are that precise. Don't use too many. Instead include collapsible sum-
  maries.

Document #2 tries to summarize the NC numbers. Remove this and instead
create a separated page for all the module (See below) based on ~/nla/rentcammer-headers-explained.md

=== Timeline

Create one.

== For All the Modules

* Determine the difference between a note noted as "Concept/Cpt" and one note using "R.C."

* Create a tentative page for ~/nla/land-use-explanation.md  

== Other Potential Sources

There are potentially other records that might hold important info:

Navigate on Arcinsys to: Archives in Niedersachsen and Bremen->Niedersächsisches Landesarchiv->Nds Landesarchiv,Abt. Bückeburg->
Amt Bückeburg (mit Amt Arensburg)->Akten
                                 ->and other

Request:
There is "Farmstead no. 14 Berenbusch"/"Die Stätte Nr. 14 zu Berenbusch" for the years "1783 - 1792". This was Carl
Friedrich Krüxckebergs Wohnort.

== NLA 139 Module

Fix the layout and margins so that, if possible, the images for each transliteration/translation pair
also appears when you click on the navigation.

== NLA Module 689

=== Double Check: Did I Add the Translation for Instances of "Exp"/"expidiert"

Find the instances of 'Exp' like, for example
...
Exp
Holste (or some other name)
17/11 (or some other date)
...

by searching for: pc '[Ee]xp' ~/nla/m/689/p/*.adoc

Translate it as: *"sent out by Holsteo on NOv. 17th"*

===  Provide a Description and Summary Each Content List Item

Explain the case file. For each number item, use the subject (the right column)
as the topic if it helps. Just work through the documents one by one and
determine what they exist, what they say, and how the Rentcammer responds.

=== Lastly Create a page for explanation of terms and concepts

Use the explanation above provide an explanation of terms (and concepts if
needed) for Rescript, dispoistive comments, an overview of the role of the Amt
and Rentcammer, whether Krueckeberg finally appeals to "Ceasar".

To do this use the glossary-like page, but rather than merely or purely a
glossary, such a glossary.adoc, create an explanation of terms and concepts that
builds on what is in glossary.adoc and overview.adocp[]

Add this page(s) to nav.adoc.

=== Other Thoughts

Make sure:
* transliterations and translations content matches
* they are not missing content found in the image(s). 
* they logically reflect the image's content
* there are necessary explanations of terms
* The initials are explained (see below)
* There is an overall summary of synopsis

Chatgpt link for analyzing documents: https://chatgpt.com/c/68df17e0-6164-8323-9013-291141655388 

=== Initials

Figure out the Amt intials vs the Rentcammer initials

1. The Amt background document has these intials: Hauck, Höcke
2. The Rentcammer has these intials: ?, ?, ?


Höcker - Amtsdiener
Reck   - Senior Privy Councilor

=== Explain Terms and Concepts

The terms in contents list, the glossary, and in the docketing information.

== Translations

Base the translation on transliteration with updated words for archaic words.
