= J. Arndt Excerpts

== Arndt pages 46-47: Einlieger

Noch 1783 war Archivassessor Clostermeier der Überzeugung, daß die
lippische Landbevölkerung zu wenig heirate und Kinder bekomme; dadurch
sei der allgemeine Wohlstand behindert. Der Beamte träumte von einer
Verdopplung der Bevölkerung in den nächsten 70 Jahren.999 Der Wegzug
von Untertanen, die Wanderarbeit in den Niederlanden und in Friesland, die
schon im 18. Jahrhundert zahlreiche Lipper über den Sommer außer Landes
lockte, versuchte die Regierung durch Verbote zu unterbinden. Zu Beginn
des 19. Jahrhunderts wurde das Verlassen des Landes zwecks auswärtiger
Arbeit nochmals eingeschränkt bzw. die bestehende Verbotslage bekräftigt,
indem alle jugendlichen Untertanen unter 20 Jahren generell im Lande
bleiben mußten, während die älteren auf einen "Erlaubnispaß" der amtlichen
Stellen angewiesen blieben. Die Steuerpflicht (Kriegssteuer und
Einliegergeld) mußte auch bei Abwesenheit und einer eventuellen
auswärtigen Veranlagung zur Einkommensteuer weiterhin erfüllt werden.
In diesem Edikt setzten sich die Bemühungen der Stände um preiswerte
Arbeitskräfte ebenso durch wie bei der Gestaltung der Gesindedienste; die
Klagen diesbezüglich wurden auf fast jedem Landtag jener Zeit vorgebracht.
So rigide die Bestimmungen waren, so wenig wurden sie eingehalten; auch
dies bemängelten die Landstände, während die Regierung es im Edikt zwar
erwähnte, hinsichtlich einer Abhilfe allerdings ratlos war.

Erst zu Beginn des 19. Jahrhunderts, verursacht durch die Agrarkrise
von 1801/02, wurde der Regierung und den Landständen bewußt, daß die
Masse der Untertanen allein kein Heilmittel für die Wirtschaftskraft des
Landes sein konnte, wenn nicht ausreichendes Einkommen in Gestalt von
festen Arbeitsplätzen zur Verfügung stand. Da man sich zu einer radikalen
Teilung der größeren Güter nicht entscheiden konnte, reglementierte man die
Vermehrung der lippischen Untertanen, die als Einlieger im Falle einer
Eheschließung mit folgendem Kindersegen zunächst von Bedürftigkeit
bedroht waren. Der Landtag 1804 darf als die Wende zu einem aktiven
Gegensteuern gegen eine unkontrollierbare Vermehrung der Unterschichten
angesehen werden; die Stände riefen nach Maßnahmen zur Eindämmung
von Heiraten der Personen, die keinen eigenen Hausstand besaßen oder
gründen konnten. Durch Verordnung wurde im Januar 1805 den
männlichen Einliegern das Erreichen des 24., den weiblichen des 20.
Lebensjahres vorgeschrieben, um heiraten zu dürfen. Auch bei Vorliegen
einer Schwangerschaft sollten die Amtsverwaltungen kein Dispensrecht
besitzen, um nicht auf diese Weise eine Umgehung der Bestimmung
herauszufordern. Der Ehekonsens wurde an den Nachweis von 100 Rtl.
Vermögen geknüpft. Die übliche Gesindedienstzeit von zwei Jahren mußte
nachgewiesen werden. Diese Entwicklung verlief zeitlich parallel zum
Umschwung der Bevölkerungspolitik auch in der angrenzenden Grafschaft
Ravensberg, wo der Rentmeister Fischer in Schildesche 1806 in seinem
Bericht "Der Zustand der Heuerlinge betreffend" die besorgniserregende
Vermehrung der ländlichen, landlosen Unterschichten in den
zurückliegenden 30 Jahren registrierte.


In den folgenden Jahren wurden in Lippe weitere Erlasse zur
Eindämmung einer Vermehrung der ärmsten Bevölkerungsschichten verfügt.
1822 fielen auch die Steuervorteile für den Anbau von Kotten und
Neuwohnerstätten fort. Die Edikte gestanden teilweise die Ohnmacht der
Regierung ein, die Bevölkerungzunahme stoppen zu können. Die Gesetze
luden geradezu zur Umgehung ein: Heiraten wurden außer Landes
vorgenommen oder das erforderliche Geld geliehen und direkt nach der Er-
teilung des amtlichen Konsenses wieder zurückgezahlt. Dieter Potente
wies darauf hin, daß die Gesetze zwar in ihrer Substanz wirkungslos blieben,
jedoch Nebeneffekte zeitigten: Die Einlieger galten bald infolge ihrer zu
großen Vermehrung im Bewußtsein der Bevölkerung als die Verursacher von
Krisen und Armutszuständen, was die Desintegration der Unterschichten
beschleunigte. Auch die als Ziel staatlicher Erziehung erkannte Hebung
der "Sittlichkeit" der Bevölkerung konnte unter diesen Umständen nicht
gefördert werden: Nicht die Fruchtbarkeit nahm ab, sondern die Zahl der
unehelich geborenen Kinder wurde höher. Hatte der Pfarrer v. Cölln noch
1784 auf den geringen Prozentsatz von unehelichen Kindern in seinem
Pfarrbezirk hingewiesen, so stieg die Zahl der unehelichen Geburten
zwischen 1770 und 1829 von 3,48 % auf 8,8 % an.


== Pages 61-62

Verfügten die Hoppenplöcker und Straßenkötter immerhin noch über einen
winzigen eigenen Grundbesitz, so mußten sich die immer zahlreicher
werdenden Einlieger auf dem Land mit einem gemieteten Haus und
gepachtetem Land begnügen. Für das Haus zahlten sie dem Eigentümer 4-6
Rtl. Miete pro Jahr; die Nahrungsmittel für den eigenen Bedarf zogen sie auf
gepachtetem Gartenland, wofür weitere Kosten von ca. 3 Rtl. jährlich
anfielen. Die Einlieger pachteten Ackerland und zogen zumeist Leinsaat
darauf, um den Rohstoff für ihre Arbeit am Spinnrad und Webstuhl selbst zu
produzieren. Alle weiteren Dinge des täglichen Bedarfs (Holz, Bretter, etwas
Vieh) bezogen sie von dem Meier, auf dessen Grund sie wohnten. Wenn sie
nicht webten oder spannen, arbeiteten sie auf dem Hof ─ entweder gegen
Tagelohn oder (wie oben gezeigt) als Dienstpflichtige ─, um ihre
Pachtverbindlichkeiten abzuleisten. Als nicht grundbesitzende Einwohner
gehörten sie nicht zu den Gemeindemitgliedern. Wichtig war für sie jedoch
die Möglichkeit, ein oder zwei Stück Vieh auf die Allmende treiben zu dürfen.

Die Einlieger traten bei Dorffesten und Hochzeiten mit ihrem Pachtherrn
zusammen auf, gehörten zu seinem "Gefolge"; da die größeren Bauern
mehrere Einlieger beschäftigten, demonstrierte die Anzahl der begleitenden
Personen in aller Öffentlichkeit den Wohlstand des Pachtherrn.1055
Die Einlieger rekrutierten sich nicht allein durch eigene Heirat und
Vermehrung, sondern bezogen darüber hinaus einen Zustrom aus
überlebenden, nichterbenden Kindern der bäuerlichen Familien, den
"Abfindlingen". Josef Mooser weist bei der sozialen Gruppe der Einlieger alle
Elemente einer Klasse nach, da weniger ihre Herkunft, als ihre Stellung im
Marktgefüge ihre Lebenschancen bestimmten. Die alte agrarische Ordnung
war im 18. Jahrhundert, ohne daß viele Verantwortliche dies wahrhaben
wollten, bereits zerfallen. In Niedersachsen trat das Problem der landlosen
unterbäuerlichen Armut in noch schärferer Form auf. Hier war das
Leinengewerbe, von einigen Gebieten im Süden abgesehen, viel weniger
verbreitet, und als wirtschaftlicher Ausweg blieb nur die Tätigkeit als
Tagelöhner übrig.1056

Footnote 1055
1055 Zur Geschichte des Einliegerstandes: Ellynor GEIGER, Die soziale Elite der
Hansestadt Lemgo und die Entstehung eines Exportgewerbes auf dem Lande in der
Zeit von 1450 bis 1650, Detmold 1976, S.34-36. Georg FUNKE, Über die Verhältnisse
der Einlieger in den Fürstentümern Lippe-Detmold und Schaumburg-Lippe, in:
Zeitschrift des Vereins für Deutsche Statistik, 2.Jg. (Berlin) 1848, S.1104-1122; hier:
S.1111; HELDMANN, Die Einlieger und deren Verhältnis zu den Colonen, vorzüglich im
Amte Oerlinghausen, in: Vaterländische Blätter 3, 1845/46, Nr.14, Sp.209-218. Die
gleichartigen Verhältnisse der Heuerlinge in der Grafschaft Ravensberg analysiert
MAGER, Protoindustrialisierung und agrarisch-gewerbliche Verflechtung, S.458-461.
Vgl. zu diesem in ganz Nordwestdeutschland verbreitetem Phänomen: WEHLER,
Deutsche Gesellschaftsgeschichte, Bd.2, S.170.

== Page 127

Auch die dem Begriff "Protoindustrialisierung" innewohnende Bedeutung
als Übergangsepoche von der feudalen und zünftig-gewerblichen
Subsistenzwirtschaft zur kapitalistischen Industrieepoche wurde mit
gewichtigen Argumenten infragegestellt: Weder lag für den ostwestfälischen
Raum eine Kommerzialisierung eines stark urbanisierten Gebietes vor, noch
trieb die städtische Nachfrage die Bauern in die Spezialisierung. Eine
Konkurrenz zwischen Handelskapital und Landwirtschaft um ländliche
Arbeitskräfte bestand nicht, und auch die intensive Bodennutzung bestand
eher auf den Pachtfeldern der Einlieger als auf den Äckern der Bauern. Vor
allem die Tatsache, daß die Industrialisierung um die Mitte des 19.
Jahrhunderts in ganz anderen Gegenden als in den früheren Leinenregionen
ihren Aufschwung nahm, daß im Gegenteil die Gebiete mit starker
Textilherstellung im gleichen Zeitraum "deindustrialisiert" wurden und sich
wieder zu Agrargebieten zurückentwickelten, hat die
"Protoindustrialisierungstheorie" an Erklärungskraft verlieren lassen.
Günter Hammer weist darauf hin, daß für Lippe die
Protoindustrialisierungstheorie nicht anwendbar ist, da weder eine Trennung
der Gebiete mit intensiver Landwirtschaft von denen der Vergewerblichung
durchgeführt werden kann noch das Maß an Urbanisierung vorlag, das die
Verfechter der Theorie ─ wohl mit Blick auf das Wuppertal ─ forderten; den
Hypothesen hinsichtlich des Bevölkerungswachstums stimmt Hammer
hingegen zu.

== Page 130
