= Page  1
#:page-role: wide

.Transliteration
[cols="1,8,2,2,2,1"]
|===
|Nrus|Designation Actorum|Amt|Jahre|Monat|Tag

|1.|Vorstellung des Colons +
Krückeberg nr:10, zu Beren +
busch, d.d.|Bburg|1798|Maÿ|29

|2.|Desfalsigeer Bericht der +
Beamten zu Buckeburg d.d.||1799|Febr|27

|3.|Concept Cammer: Rescripts +
andjedachte Beamte, d.d.||1800|Oct|18

|4.|Bericht von denselben Beamten||1800|Oct|18

|4 1/2.|dazu gehöriger Bericht +
von Lteutenant Funiz||||

|5.|Concept Cammer: Rasiripts +
am die Beamte yu Buckeburg +
desgle an den Bammewrantu +
meister Haukmann d.d.||||27

|6.|Concept Kaufbriefes der Rentkammer +
für den Colon Krückeberg nr: 10 +
zu Berenbusch über einen Platz +
zur Vergrößerung seines Garkens|||Dec|1
|===

* Designation Actorum -- "Record of proceedings" or "Designation of the records"; or maybe “List of the plaintiffs” or “Designation of parties”  
* d.d. -- *de dato*, which is Latin for "of the date" or "dated."

.Translation
[cols="1,5,2,2,2,1"]
|===
|Nrus|Record of the Proceedings/ +
Minutes of the Meetings	|Amt|Jahre|Monat|Tag

|1.|Presentation/Submission by Colonist Krückeberg, No. 10, of Berenbusch, dated|Bückeburg|1798|May|29
|===

 
