= Johann Heinrich Krückeberg's Recorded Answers 

TODO: 
* Give German/English titles and the URL to Arcinsys.'
* Mention this is Dr. Moehle finding:

The householders are each asked 40 questions. The questions are
unfortunately not documented in this file, so we get to know only the
answers. Many of the questions were negated by recording either ‚nescit‘
(he does not know) or ‚cessat‘ (does not apply, falls away), but we do
not know what the topics were that this refers to. Also, some questions
are answered by ‚ut reliqui‘, which means he had the same conditions as
all the others.

.Latin terms used
[cols="1,2,2", with="70%"]
|===
| Latin term   | Literal meaning       | Archival meaning                |

| *nescit*     | he does not know      | Respondent has no knowledge     |

| *cessat*     | it ceases / is absent | Not applicable / does not exist |

| *ut reliqui* | like the others       | Same as other respondents       |
|==

NOTE: The fact that *Johann Heinrich Krückeberg says he married into the
property*, and that he does not appear in lists earlier than the 1740s,
MIGHT indicate a second marriage around that time.

Transcript of the report for Johann Heinrich Krückeberg at Berenbusch
no. X

.Transliteration
[literal.bordered,subs="verbatim,quotes"]
....
N. X [Rf?] er hiesse

1. Johann Henrich Krückeberg

vormahls Friedrich Kuhlmann auch

Joh. Tönnies Eggerding

2. habe darauf geheyrahtet

3. ein Brinksitzer

4. Er habe nichts als einen Garten

worin zugl. etwas Saatlandt

Nach der neuen Messung.

5. cessat

6 er habe kein Rottland ausser

dem Garthen

7. Sey Illmo eigen.

8. Wöchentl. Dienste verrichte er [symbol = nicht; old code for
‚not‘]

9. jährl. 12 Burgfesten

10. cessat

11. funff Erndte Tage

12. so offt es nöhtig

13. so offt es erforderlig [bei anderen: Landfolge mit der Hand]

14. 15. 16. ut reliqui [bei anderen: auch Jagd und Wachten]

17. cessat

18. [Dues]

a) contribat 2 [Groschen] 2 [Pfennige]

b) Rottzinß 11 [Groschen]

c) Mahl[...] 12 [Groschen]

d) Michael Schatz cessit

e) –

f) – 4 [Pfennige]

g) Landschatz gibt er nicht weilen

er kein Land habe

h) nescit

i) ut reliqui

k) Viehschatz p nro. des Viehes

4 mgr [Groschen] 4 Pf [Pfennige] auch 8 mgr [Groschen]

l) cessat

m) Ein Rauchhuhn an gdste Herrschafft

n) nescit

19)

a) ut reliqui

b) Erbe 3 rthlr [Taler] 4 mgr [Groschen] 4 Pf [Pfennige]

c-g nescit

20-23 cessat

24. 1 Kuh 1 Rind

1 Schwein

25. treibe solche vor den Hirten

26. nein

27-31 cessat

32. Er gebe niemand

etwas als dem

pastori und Küster

das gewöhnliche

33. nein

34. Vermeyne, da er

keine Länderey

habe, solche nicht

schuldig zu seyn

35. nein

36, 37 cessat

38. nein

39. ut reliqui

40. Er samle

das Holtz in

der Waldung

oder kauffe es.

_Translation_

1. Johann Henrich Krückeberg,

formerly Friedrich Kuhlmann, also

Joh. Tönnies Eggerding,

2. has married into this property.

3. A tenant farmer.

4. He has nothing but a garden,

in which there is also some arable land.

According to the new measurement.

5. cessat

6 He has no land except

the garden.

7. Belongs to the Prince.

8. He does nor perform weekly services [symbol = not; old code
for ‘not’]

9. 12 times a year service at the castle [possibly building work]

10. cessat

11. five harvest days

12. as often as necessary

13. as often as required [in others: land cultivation by hand]

14. 15. 16. ut reliqui [in others: also hunting and guard duty]

17. cessat

18. [Dues]

a) contributes 2 [Groschen] 2 [Pfennige]

b) Rottzinß 11 [Groschen]

c) Mill[...] 12 [Groschen]

d) Michael tax cessit

e) –

f) – 4 [Pfennige]

g) He does not pay land tax because

he has no land.

h) nescit

i) ut reliqui

k) Livestock tax p no. of livestock

4 mgr [Groschen] 4 Pf [Pfennige] also 8 mgr [Groschen]

l) cessat

m) One smoked chicken to His Lordship

n) nescit

19)

a) ut reliqui

b) Inheritance 3 rthlr [Taler] 4 mgr [Groschen] 4 Pf [Pfennige]

c-g nescit

20-23 cessat

24. 1 cow 1 ox

1 pig

25. He lets the shepherd care for them

26. no

27-31 cessat

32. He gives nothing to anyone

except to the

Pastor and sexton

the usual

33. no

34. He thinks, since he

has no land

he is therefore not

obligated to do so

35. no

36, 37 cessat

38. no

39. ut reliqui

40. He gathers

the wood in

the forest

or purchase it.
....
