= NC 4731

....
NC 4731                                 Jst. ml. 8/8.49.
Nr. pr. 1313                            Pr. am Amts 15/8 49
Stp. 3g.



[clerk's initials:] L   W

L  Eine Unterfahnigste Bitte an Hochfürstliche Renntkammer
W. Ich bin willens, Meine Coloni zu verkaufen, und nach Amehrika
   auszuwandern, und bin mit den Käufer Einlieges Borneman
   von Nordholtz wegen dem Kaufpreiß Einig, welches wir den
   Amte angezeigt haben und da ich willens bin auf den 15ten
   September abzureisen, weil auf den 15ten September ein
   Schif zu meiner Reise abgeht, und ich mein inventarium
   noch zu verkaufen habe, und übrigens zu entrichten habe; so
   Bitte ich Hochfürstliche Rentkammer um Schleunige nachricht
   so bald als möglich, Untertähnigst Bitteinhalss
   
   Untertähnigster Colon Krückeberg Nro 10 in Behrenbusch
                           d 8ten August 1849

                     NC 7 Tr. m. zum Berichte an das
                     Amt Bückeburg 12 mpt Stempel
                     strafe sind einzuziehen und
                     eingesenden
                     Bbg 13/8 49
                     Barkhause
....
