= Survey of House and Property Holders in the District of Bückeburg as Part of a General Land Survey (1737) 

== Findings

The document *Erfassung der Haus- und Hofbesitzer im Amt Bückeburg im Rahmen
einer Generallandesvisitation (Landesvermessung) ("Registration of house
and farm owners in the Bückeburg district as part of a general land survey
(state land survey)"* has identifier
link:https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4894569[NLA
BU L 2 L Nr. 27/28] in
link:https://www.arcinsys.niedersachsen.de/arcinsys/start.action[Arcinsys].

== No Krückeberg is a Brinksitzer in Berenbusch in 1737 

Dr. Sylvia Möhle, who examined this document in the Bückeburg archive,
found no Krückeberg who was a Brinksitzer in Berenbusch in 1737, the year of
this document:

[quote, Dr Sylvia Möhle's findings]
____
Berenbusch – the ‚Brinksitzer‘ properties belonged to the Prince and tax
has to be paid to him, as is noted on the right side of this page. Among
the property owners there is *no Krückeberg*, nor do the names of his
predecessors *Kuhlmann* and *Eggerding* appear.
____

[IMPORTANT]
====
This would seem to imply that by 1743-1744, no. 10 Berenbusch had passed
from Eggerding to Kuhlmann and then to Johann Heinrich Krückeberg,
something that warrants closer re-examination.
====
