= Survey of House and Property Holders in the District of Bückeburg as Part of a General Land Survey (1737) 

== Findings

The document *Erfassung der Haus- und Hofbesitzer im Amt Bückeburg im Rahmen
einer Generallandesvisitation (Landesvermessung) ("Registration of house
and homestead owners in the Bückeburg district as part of a general land survey
(state land survey)"* has identifier
link:https://www.arcinsys.niedersachsen.de/arcinsys/detailAction?detailid=v4894569[NLA
BU L 2 L Nr. 27/28] in
link:https://www.arcinsys.niedersachsen.de/arcinsys/start.action[Arcinsys].

== No Krückeberg is a Brinksitzer in Berenbusch in 1737 

Dr. Sylvia Möhle, who examined this document in the Bückeburg archive,
found no Krückeberg who was a Brinksitzer in Berenbusch in 1737, the year of
this document:

[quote, Dr Sylvia Möhle's findings]
____
Berenbusch – the ‚Brinksitzer‘ properties belonged to the Prince and tax
has to be paid to him, as is noted on the right side of this page. Among
the property owners there is *no Krückeberg*, nor do the names of his
predecessors *Kuhlmann* and *Eggerding* appear.
____

[IMPORTANT]
====
This would seem to imply that by 1743-1744, *no. 10 Berenbusch* had passed
from xref:140:page-17.adoc[Johann Tönnis Eggerding] to xref:2741:krueckeberg-answers.adoc[Frierich
Kuhlmann] and then to xref:140:page-17.adoc[Johann Heinrich Krückeberg],
something that warrants closer re-examination.

The 1747 *List of names of all colonists in the districts of Bückeburg
and Arensburg, with numbering of all houses* ("Namensverzeichnis sämtlicher
Kolonen der Ämter Bückeburg und Arensburg, mit Nummerierung der sämtlichen
Häuser") lists all the xref:140:page-17.adoc[Brinksitzers in Berenbsuch].
No. 10 Berenbusch is among these:

....
10.) Joh. Tönnies Eggerding modo Joh. Heinr. Kruckeberg
....

or 

....
Johann Tönnies Eggerding, now Johann Heinrich Krückeberg.
....

We know that Johann Tönnis Eggerding preceded Johann Heinrich as holder
of *no. 10 Berenbusch*, but he was not the immediate predecessor to Johann
Heinrich. The *Records of the questioning of the individual rural property
holders in Evesen, Berenbusch, Nordholz, and Rusbend in the context of the
General Land Survey* from 1743-1744, whose questions are unknown (we only
have the replies), has this reply by Johann Heinrich Krückeberg to the
first question:

....
1. Johann Henrich Krückeberg
vormahls Friedrich Kuhlmann auch
Joh. Tönnies Eggerding  
....

While the questions have not been presevered, this does tells us:

....
1. Johann Henrich Krückeberg,
formerly Friedrich Kuhlmann, also
Joh. Tönnies Eggerding
....
====
